Nomina1/Sistema Nomina Web/Sistema Nomina Web/Controllers/IncidenciasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sistema_Nomina_Web.Models.dbModels;

namespace Sistema_Nomina_Web.Controllers
{
    [Authorize]
    public class IncidenciasController : Controller
    {
        private readonly DB_NominaContext _context;

        public IncidenciasController(DB_NominaContext context)
        {
            _context = context;
        }

        // GET: Incidencias
        public async Task<IActionResult> Index()
        {
            var dB_NominaContext = _context.Incidencia.Include(i => i.PeriodoNomina).Include(i => i.Trabajador);
            return View(await dB_NominaContext.ToListAsync());
        }

        // GET: Incidencias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Incidencia == null)
            {
                return NotFound();
            }

            var incidencium = await _context.Incidencia
                .Include(i => i.PeriodoNomina)
                .Include(i => i.Trabajador)
                .FirstOrDefaultAsync(m => m.IncidenciaId == id);
            if (incidencium == null)
            {
                return NotFound();
            }

            return View(incidencium);
        }

        // GET: Incidencias/Create
        public IActionResult Create()
        {
            ViewData["PeriodoNominaId"] = new SelectList(_context.PeriodoNominas, "PeriodoNominaId", "PeriodoNominaId");
            ViewData["TrabajadorId"] = new SelectList(_context.Trabajadors, "TrabajadorId", "Nombre");
            return View();
        }

        // POST: Incidencias/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IncidenciaId,TrabajadorId,PeriodoNominaId,Faltas,HorasExtra,Fecha")] Incidencium incidencium)
        {
            if (ModelState.IsValid)
            {
                // Agrega valores predeterminados si es necesario
                incidencium.Faltas = incidencium.Faltas ?? 0;
                incidencium.HorasExtra = incidencium.HorasExtra ?? 0;

                _context.Add(incidencium);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["PeriodoNominaId"] = new SelectList(_context.PeriodoNominas, "PeriodoNominaId", "PeriodoNominaId", incidencium.PeriodoNominaId);
            ViewData["TrabajadorId"] = new SelectList(_context.Trabajadors, "TrabajadorId", "Nombre", incidencium.TrabajadorId);
            return View(incidencium);
        }

        // GET: Incidencias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Incidencia == null)
            {
                return NotFound();
            }

            var incidencium = await _context.Incidencia.FindAsync(id);
            if (incidencium == null)
            {
                return NotFound();
            }
            ViewData["PeriodoNominaId"] = new SelectList(_context.PeriodoNominas, "PeriodoNominaId", "PeriodoNominaId", incidencium.PeriodoNominaId);
            ViewData["TrabajadorId"] = new SelectList(_context.Trabajadors, "TrabajadorId", "Nombre", incidencium.TrabajadorId);
            return View(incidencium);
        }

        // POST: Incidencias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IncidenciaId,TrabajadorId,PeriodoNominaId,Faltas,HorasExtra,Fecha")] Incidencium incidencium)
        {
            if (id != incidencium.IncidenciaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(incidencium);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IncidenciumExists(incidencium.IncidenciaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PeriodoNominaId"] = new SelectList(_context.PeriodoNominas, "PeriodoNominaId", "PeriodoNominaId", incidencium.PeriodoNominaId);
            ViewData["TrabajadorId"] = new SelectList(_context.Trabajadors, "TrabajadorId", "TrabajadorId", incidencium.TrabajadorId);
            return View(incidencium);
        }

        // GET: Incidencias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Incidencia == null)
            {
                return NotFound();
            }

            var incidencium = await _context.Incidencia
                .Include(i => i.PeriodoNomina)
                .Include(i => i.Trabajador)
                .FirstOrDefaultAsync(m => m.IncidenciaId == id);
            if (incidencium == null)
            {
                return NotFound();
            }

            return View(incidencium);
        }

        // POST: Incidencias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Incidencia == null)
            {
                return Problem("Entity set 'DB_NominaContext.Incidencia'  is null.");
            }
            var incidencium = await _context.Incidencia.FindAsync(id);
            if (incidencium != null)
            {
                _context.Incidencia.Remove(incidencium);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IncidenciumExists(int id)
        {
          return (_context.Incidencia?.Any(e => e.IncidenciaId == id)).GetValueOrDefault();
        }
    }
}

Nomina1/Sistema Nomina Web/Sistema Nomina Web/Controllers/TipoJornadaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sistema_Nomina_Web.Models.dbModels;

namespace Sistema_Nomina_Web.Controllers
{
    [Authorize]
    public class TipoJornadaController : Controller
    {
        private readonly DB_NominaContext _context;

        public TipoJornadaController(DB_NominaContext context)
        {
            _context = context;
        }

        // GET: TipoJornada
        public async Task<IActionResult> Index()
        {
              return _context.TipoJornada != null ? 
                          View(await _context.TipoJornada.ToListAsync()) :
                          Problem("Entity set 'DB_NominaContext.TipoJornada'  is null.");
        }

        // GET: TipoJornada/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TipoJornada == null)
            {
                return NotFound();
            }

            var tipoJornadum = await _context.TipoJornada
                .FirstOrDefaultAsync(m => m.TipoJornadaId == id);
            if (tipoJornadum == null)
            {
                return NotFound();
            }

            return View(tipoJornadum);
        }

        // GET: TipoJornada/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TipoJornada/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TipoJornadaId,Descripcion,HorasJornada")] TipoJornadum tipoJornadum)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tipoJornadum);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tipoJornadum);
        }

        // GET: TipoJornada/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TipoJornada == null)
            {
                return NotFound();
            }

            var tipoJornadum = await _context.TipoJornada.FindAsync(id);
            if (tipoJornadum == null)
            {
                return NotFound();
            }
            return View(tipoJornadum);
        }

        // POST: TipoJornada/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TipoJornadaId,Descripcion,HorasJornada")] TipoJornadum tipoJornadum)
        {
            if (id != tipoJornadum.TipoJornadaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tipoJornadum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TipoJornadumExists(tipoJornadum.TipoJornadaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tipoJornadum);
        }

        // GET: TipoJornada/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TipoJornada == null)
            {
                return NotFound();
            }

            var tipoJornadum = await _context.TipoJornada
                .FirstOrDefaultAsync(m => m.TipoJornadaId == id);
            if (tipoJornadum == null)
            {
                return NotFound();
            }

            return View(tipoJornadum);
        }

        // POST: TipoJornada/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TipoJornada == null)
            {
                return Problem("Entity set 'DB_NominaContext.TipoJornada'  is null.");
            }
            var tipoJornadum = await _context.TipoJornada.FindAsync(id);
            if (tipoJornadum != null)
            {
                _context.TipoJornada.Remove(tipoJornadum);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TipoJornadumExists(int id)
        {
          return (_context.TipoJornada?.Any(e => e.TipoJornadaId == id)).GetValueOrDefault();
        }
    }
}

Nomina1/Sistema Nomina Web/Sistema Nomina Web/Controllers/TipoSalarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sistema_Nomina_Web.Models.dbModels;

namespace Sistema_Nomina_Web.Controllers
{
    [Authorize]
    public class TipoSalarioController : Controller
    {
        private readonly DB_NominaContext _context;

        public TipoSalarioController(DB_NominaContext context)
        {
            _context = context;
        }

        // GET: TipoSalario
        public async Task<IActionResult> Index()
        {
              return _context.TipoSalarios != null ? 
                          View(await _context.TipoSalarios.ToListAsync()) :
                          Problem("Entity set 'DB_NominaContext.TipoSalarios'  is null.");
        }

        // GET: TipoSalario/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TipoSalarios == null)
            {
                return NotFound();
            }

            var tipoSalario = await _context.TipoSalarios
                .FirstOrDefaultAsync(m => m.TipoSalarioId == id);
            if (tipoSalario == null)
            {
                return NotFound();
            }

            return View(tipoSalario);
        }

        // GET: TipoSalario/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TipoSalario/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TipoSalarioId,Descripcion,Periodicidad")] TipoSalario tipoSalario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tipoSalario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tipoSalario);
        }

        // GET: TipoSalario/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TipoSalarios == null)
            {
                return NotFound();
            }

            var tipoSalario = await _context.TipoSalarios.FindAsync(id);
            if (tipoSalario == null)
            {
                return NotFound();
            }
            return View(tipoSalario);
        }

        // POST: TipoSalario/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TipoSalarioId,Descripcion,Periodicidad")] TipoSalario tipoSalario)
        {
            if (id != tipoSalario.TipoSalarioId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tipoSalario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TipoSalarioExists(tipoSalario.TipoSalarioId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tipoSalario);
        }

        // GET: TipoSalario/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TipoSalarios == null)
            {
                return NotFound();
            }

            var tipoSalario = await _context.TipoSalarios
                .FirstOrDefaultAsync(m => m.TipoSalarioId == id);
            if (tipoSalario == null)
            {
                return NotFound();
            }

            return View(tipoSalario);
        }

        // POST: TipoSalario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TipoSalarios == null)
            {
                return Problem("Entity set 'DB_NominaContext.TipoSalarios'  is null.");
            }
            var tipoSalario = await _context.TipoSalarios.FindAsync(id);
            if (tipoSalario != null)
            {
                _context.TipoSalarios.Remove(tipoSalario);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TipoSalarioExists(int id)
        {
          return (_context.TipoSalarios?.Any(e => e.TipoSalarioId == id)).GetValueOrDefault();
        }
    }
}

Nomina1/Sistema Nomina Web/Sistema Nomina Web/Views/Trabajador/Create.cshtml
@model Sistema_Nomina_Web.Models.dbModels.Trabajador

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Trabajador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rfc" class="control-label"></label>
                <input asp-for="Rfc" class="form-control" />
                <span asp-validation-for="Rfc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Curp" class="control-label"></label>
                <input asp-for="Curp" class="form-control" />
                <span asp-validation-for="Curp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nss" class="control-label"></label>
                <input asp-for="Nss" class="form-control" />
                <span asp-validation-for="Nss" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label"></label>
                <input asp-for="FechaInicio" class="form-control" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoJornadaId" class="control-label"></label>
                <select asp-for="TipoJornadaId" class ="form-control" asp-items="ViewBag.TipoJornadaId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TipoSalarioId" class="control-label"></label>
                <select asp-for="TipoSalarioId" class ="form-control" asp-items="ViewBag.TipoSalarioId"></select>
            </div>
            <div class="form-group">
                <label asp-for="SalarioBase" class="control-label"></label>
                <input asp-for="SalarioBase" class="form-control" />
                <span asp-validation-for="SalarioBase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PeriodicidadId" class="control-label"></label>
                <select asp-for="PeriodicidadId" class ="form-control" asp-items="ViewBag.PeriodicidadId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Nomina1/Sistema Nomina Web/Sistema Nomina Web/Views/Trabajador/Delete.cshtml
@model Sistema_Nomina_Web.Models.dbModels.Trabajador

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trabajador</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rfc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rfc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Curp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Curp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nss)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nss)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SalarioBase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SalarioBase)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Periodicidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Periodicidad.PeriodicidadId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Activo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Activo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoJornada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoJornada.TipoJornadaId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoSalario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoSalario.TipoSalarioId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TrabajadorId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Nomina1/Sistema Nomina Web/Sistema Nomina Web/Views/Trabajador/Details.cshtml
@model Sistema_Nomina_Web.Models.dbModels.Trabajador

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Trabajador</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rfc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rfc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Curp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Curp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nss)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nss)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SalarioBase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SalarioBase)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Periodicidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Periodicidad.PeriodicidadId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Activo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Activo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoJornada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoJornada.TipoJornadaId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoSalario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoSalario.TipoSalarioId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.TrabajadorId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Nomina1/Sistema Nomina Web/Sistema Nomina Web/Views/Trabajador/Index.cshtml
@model IEnumerable<Sistema_Nomina_Web.Models.dbModels.Trabajador>

@{
    ViewData["Title"] = "Index";
}

<!-- DataTables CSS -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.5/css/jquery.dataTables.min.css">

<!-- jQuery (necesario para DataTables) -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- DataTables JS -->
<script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>
<style>body {
        background: linear-gradient(to bottom, #A3D5FF, #E3F2FD);
        color: #000000; /* Letras en negro */
        font-family: system-ui, -apple-system, sans-serif;
    }</style>

<h1>Lista de empleados</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Crear Nuevo Empleado</a>
</p>
<div class="btn-group" role="group">
    <a class="btn btn-secondary" asp-controller="TipoJornada" asp-action="Index">Ver Tipos de Jornada</a>
    <a class="btn btn-secondary" asp-controller="Incidencias" asp-action="Index">Ver Incidencias</a>
    <a class="btn btn-secondary" asp-controller="TipoSalario" asp-action="Index">Ver Tipos de Salario</a>
    <a class="btn btn-secondary" asp-controller="Periodicidad" asp-action="Index">Ver Periodicidades</a>
</div>

<div style="overflow-x:auto;">
    <table id="empleadosTable" class="display table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Nombre)</th>
                <th>@Html.DisplayNameFor(model => model.Rfc)</th>
                <th>@Html.DisplayNameFor(model => model.Curp)</th>
                <th>@Html.DisplayNameFor(model => model.Nss)</th>
                <th>@Html.DisplayNameFor(model => model.FechaInicio)</th>
                <th>@Html.DisplayNameFor(model => model.SalarioBase)</th>
                <th>@Html.DisplayNameFor(model => model.Periodicidad.Nombre)</th>
                <th>@Html.DisplayNameFor(model => model.Activo)</th>
                <th>@Html.DisplayNameFor(model => model.TipoJornada.Descripcion)</th>
                <th>@Html.DisplayNameFor(model => model.TipoSalario.Descripcion)</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                    <td>@Html.DisplayFor(modelItem => item.Rfc)</td>
                    <td>@Html.DisplayFor(modelItem => item.Curp)</td>
                    <td>@Html.DisplayFor(modelItem => item.Nss)</td>
                    <td>@Html.DisplayFor(modelItem => item.FechaInicio)</td>
                    <td>@Html.DisplayFor(modelItem => item.SalarioBase)</td>
                    <td>@Html.DisplayFor(modelItem => item.Periodicidad.Nombre)</td>
                    <td>@Html.DisplayFor(modelItem => item.Activo)</td>
                    <td>@Html.DisplayFor(modelItem => item.TipoJornada.Descripcion)</td>
                    <td>@Html.DisplayFor(modelItem => item.TipoSalario.Descripcion)</td>
                    <td>
                        <a class="btn btn-warning btn-sm" asp-action="Edit" asp-route-id="@item.TrabajadorId">Editar</a>
                        <a class="btn btn-info btn-sm" asp-action="Details" asp-route-id="@item.TrabajadorId">Detalles</a>
                        <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@item.TrabajadorId">Eliminar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<!-- Inicializar DataTables con scroll horizontal -->
<script>
    $(document).ready(function () {
        $('#empleadosTable').DataTable({
            "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.13.5/i18n/Spanish.json"
            },
            "pageLength": 10,
            "lengthMenu": [5, 10, 25, 50],
            "order": [[0, 'asc']],
            "scrollX": true, // Habilita el scroll horizontal
            "columnDefs": [
                { "orderable": false, "targets": -1 } // Desactiva la ordenación en la columna de acciones
            ]
        });
    });
</script>